/**
 * Check the current time of the player; set nextDescription to the next available entry.<br>
 * If the next description is over 6 seconds away, send a screenreader message to notify the user. 
 * @param {Object} player generated by YT API
 */
export const checkNextDescriptionTime = function(player){

    let time = player.getCurrentTime();
    let nextDescription = Math.floor(this.timeline.find(entry => (entry.startS >= time && entry.endS >= time)).startS-time);
    // If the next description is a while away (over six seconds), let the user know through their screen reader of choice.
    if (nextDescription > 6 && typeof (window as any).StatusVO != undefined) {
        (window as any).StatusVO.update(`audio description starting in ${nextDescription} seconds`)
    };

}